### ISSUE TITLE
Repurpose DENO_DIR to deno's user home

### ISSUE THREAD

**Issue by x80486** [denoland/deno_docker#109]
Would be better to change `DENO_DIR` to use `deno`'s user home instead of `/deno-dir/`?

Eventually, this is not an issue with the image, but something I'm facing with GitLab CI (and probably some other solutions) that it complains about caching folders outside the `build` (or user's home) sub-directory.

**Comment by hayd** [comment]
What did you have to set DENO_DIR to for gitlab-ci?

**Comment by x80486** [comment]
The original file was like this:

```yaml
default:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - $DENO_DIR/
  image: docker.io/hayd/alpine-deno:1.7.2 # https://hub.docker.com/r/hayd/alpine-deno/

stages:
  - verify

format:
  stage: verify
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_MERGE_REQUEST_ID
  script:
    - deno fmt --check
```

Removing the `cache` key it's all I needed to remove the warnings and make the pipeline works without failing. I think setting `DENO_DIR` to `/home/deno/.cache/deno` (the defaults) makes sense and should probably fix this.
